language: c

install:
  - mkdir ~/toolchain
  - "[ $RTT_TOOL_CHAIN = 'sourcery-arm' ] && curl -s https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2011.03-42-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 | tar xjf - -C ~/toolchain && export RTT_EXEC_PATH=~/toolchain/arm-2011.03/bin || true"

before_script:
  - export RTT_ROOT=`pwd`
  - export RTT_CC='gcc'

script:
  - scons -C bsp/$RTT_BSP

notifications:
  email: false

env:
  - RTT_BSP='at91sam9260' RTT_TOOL_CHAIN='sourcery-arm' 
#  - RTT_BSP='avr32uc3b0'
#  - RTT_BSP='bf533'
#  - RTT_BSP='dev3210'
  - RTT_BSP='efm32' RTT_TOOL_CHAIN='sourcery-arm' 
#  - RTT_BSP='jz47xx'
  - RTT_BSP='lm3s8962' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='lm3s9b9x' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='lm4f232' RTT_TOOL_CHAIN='sourcery-arm' 
#  - RTT_BSP='lpc1114' # no scons
#  - RTT_BSP='lpc122x' # no scons
  - RTT_BSP='lpc176x' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='lpc178x' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='lpc2148' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='lpc2478' RTT_TOOL_CHAIN='sourcery-arm' 
#  - RTT_BSP='ls1bdev'
#  - RTT_BSP='m16c62p'
  - RTT_BSP='mb9bf500r' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='mb9bf506r' RTT_TOOL_CHAIN='sourcery-arm' 
#  - RTT_BSP='microblaze'
  - RTT_BSP='mini2440' RTT_TOOL_CHAIN='sourcery-arm' 
#  - RTT_BSP='mini4020' # no scons
#  - RTT_BSP='nios_ii'
#  - RTT_BSP='nuc140'
#  - RTT_BSP='pic32ethernet'
#  - RTT_BSP='sam7s' # no scons
  - RTT_BSP='sam7x' RTT_TOOL_CHAIN='sourcery-arm'
#  - RTT_BSP='simulator' # x86
  - RTT_BSP='stm32f0x' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='stm32f107' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='stm32f10x' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='stm32f20x' RTT_TOOL_CHAIN='sourcery-arm' 
  - RTT_BSP='stm32f40x' RTT_TOOL_CHAIN='sourcery-arm' 
#  - RTT_BSP='taihu'
#  - RTT_BSP='upd70f3454'
#  - RTT_BSP='wh44b0'
#  - RTT_BSP='x86' # x86
#  - RTT_BSP='xplorer4330'
